# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_event_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('event_type', models.CharField(choices=[('SIGNUP_COMPLETED', 'Signup Completed'), ('MOVIE_VIEWED', 'Movie Viewed'), ('SEARCH_PERFORMED', 'Search Performed'), ('ADD_TO_CART', 'Add To Cart'), ('CHECKOUT_STARTED', 'Checkout Started'), ('CHECKOUT_ABANDONED', 'Checkout Abandoned'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PURCHASE_COMPLETED', 'Purchase Completed'), ('WATCH_COMPLETED', 'Watch Completed'), ('CONCIERGE_REQUESTED', 'Concierge Requested'), ('RECOMMENDATION_VIEWED', 'Recommendation Viewed'), ('RECOMMENDATION_CLICKED', 'Recommendation Clicked')], max_length=40)),
                ('customer_ref', models.CharField(blank=True, max_length=80)),
                ('movie_ref', models.CharField(blank=True, max_length=80)),
                ('checkout_ref', models.CharField(blank=True, max_length=80)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('n8n_status', models.CharField(choices=[('pending', 'Pending'), ('not_configured', 'Not Configured'), ('forwarded', 'Forwarded'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='checkout.checkout')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
    ]
