# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='movies.movie'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'timestamp'], name='events_even_event_t_19b40a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['customer', 'timestamp'], name='events_even_custome_bb6d3c_idx'),
        ),
    ]
