# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('genre', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=80)),
                ('language', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Runtime in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poster', models.CharField(max_length=255)),
                ('backdrop', models.CharField(max_length=255)),
                ('palette', models.JSONField(default=dict)),
                ('motif', models.PositiveSmallIntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('trending_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watches', to='movies.movie')),
            ],
            options={
                'verbose_name_plural': 'watch history',
                'ordering': ['-watched_at'],
            },
        ),
    ]
